# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f980749e0070c8a8ecffa165d458479d37754f5261dde1e4ad48deb73f5ab56d44166a9e08b2db6a0cb1a102b15eef670bc3067763a7b645fe925f34478d3f0d

test:
  secret_key_base: 522a7cf7996576d472f47fc56a14db088fc79b0e010fbe2699bfb800cab21b619ff38d3c767517f43acf42239cf2dbdbc4a3113200d20512d8fac9a559c42b7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
